"""Added finalize table

Revision ID: 3e18ed214541
Revises: 3f4dce7266b1
Create Date: 2026-06-12 09:09:36.469287

"""

from typing import Sequence, Union

from alembic import op
from pir_pipeline.models.pir_sql_models import finalize_query

# revision identifiers, used by Alembic.
revision: str = "3e18ed214541"
down_revision: Union[str, Sequence[str], None] = "3f4dce7266b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(finalize_query)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW finalize")
    # ### end Alembic commands ###
