# Adapted from Claude 3.7s
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: >
  Lambda function for linking Program Information Report (PIR) data

Resources:
  PIRLinker:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: pir_linker/
      Handler: app.lambda_handler
      Runtime: python3.12
      Timeout: 600
      MemorySize: 2048
      Environment:
        Variables:
          RDS_ENDPOINT:
          DB_HOST:
          DB_PORT:
          DB_USER:
          DB_PASSWORD:
          DB_NAME:
